
/*
* @author: Laure Buysse
* @file: buttonDriver
*/

#include "stdio.h"
#include"MK64F.h"

/**
*
* void SW2Init(void)
*
* Summary of the SW2Init function:
*
*   The SW2Init will initialise switch 2 on the k64F MBED board. This means
*   it also configures the IRQC for the switch.
*   Note that the switch is situated at Port C, bit 6
*
*/
void SW2Init(){
  	SIM->SCGC5 |= SIM_SCGC5_PORTC_MASK; //Enable port C Clock Gate Control for switch

    PORTC->PCR6 = 0x90100;              //ISF (24): set high for detection  interrupt
                                        //IRQC (16-19): interrupt on rising-edge: 0b1001
                                        //MUX(8-10): configure as GPIO (Alternative 1): 0b001

    PORTC->PDDR |= (0 << 6);            //Configure switch as Input

    PORT_C->ISFR = PORT_ISFR_ISF(0x40); //Clear interrupt status flag
    NVIC_EnableIRQ(PORTC_IRQn);         //Enable the interrupt
}

/**
*
* void PORTC_IRQHandler(void)
*
* Summary of the PORTC_IRQHandler function:
*
*   When an interrupt is generated by PORTC (by pressing switch 2) this IRQ-
*   Handler will handle the interrupt.
*   Swtich 2 is pressed to turn the alarm on or off, so the IRQ_Handler will
*   toggle the alarmstatus when the button is pressed. An LED will tell the user
*   whether the alarm switched on or off.
*
*/
void PORTC_IRQHandler(void){
  onOff = !onOff;                     //Toggle the alarmstatus
  //Check whether the alarmstatus is acive or inactive
  if(onOff == true){
      //alarmstatus is active, turn LED(Green) on
      GPIOE->PDOR |= (0 << 26);
  }
  else{
    //alarmstatus is inactive, turn LED(Green) off
    GPIOE->PDOR |= (1 << 26);
  }

  PORTC_ISFR = PORT_ISFR_ISF(0x40);   //Clear interrupt status flag
}
